// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repository.go -destination=internal/mock_repository/repository_mock.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository
