// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/withdraw_requests_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/withdraw_requests_repository.go -destination=internal/mock_repository/withdraw_requests_repository_mock.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/WorstOfAny/go-musthave-diploma-work/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawRequestRepository is a mock of WithdrawRequestRepository interface.
type MockWithdrawRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockWithdrawRequestRepositoryMockRecorder is the mock recorder for MockWithdrawRequestRepository.
type MockWithdrawRequestRepositoryMockRecorder struct {
	mock *MockWithdrawRequestRepository
}

// NewMockWithdrawRequestRepository creates a new mock instance.
func NewMockWithdrawRequestRepository(ctrl *gomock.Controller) *MockWithdrawRequestRepository {
	mock := &MockWithdrawRequestRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawRequestRepository) EXPECT() *MockWithdrawRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWithdrawRequestRepository) Create(arg0 context.Context, arg1 models.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWithdrawRequestRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWithdrawRequestRepository)(nil).Create), arg0, arg1)
}

// List mocks base method.
func (m *MockWithdrawRequestRepository) List(arg0 context.Context, arg1 int) ([]models.WithdrawRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]models.WithdrawRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWithdrawRequestRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWithdrawRequestRepository)(nil).List), arg0, arg1)
}
